
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-7
pull_requests: [{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-announcement-button","number":36,"title":"zc - add announcements button on commons list page","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/36"},{"author":{"id":"U_kgDOBYEQGw","is_bot":false,"login":"nadavital","name":"Nadav Avital"},"headRefName":"nadav-pitestFix","number":35,"title":"na - updated pom.xml for partial pitest runs","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/35"},{"author":{"id":"U_kgDOBYEQGw","is_bot":false,"login":"nadavital","name":"Nadav Avital"},"headRefName":"nadav-AnnouncementBugFix","number":32,"title":"na - Fixed Announcement POST Bug","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/32"},{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-dev","number":28,"title":"zc - Fixed dateConversion test file","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/28"},{"author":{"id":"U_kgDOBanq-A","is_bot":false,"login":"YixinXue","name":"The boyhood"},"headRefName":"Yixin-incorporate","number":26,"title":"Yixin - incorporate announcement card component to play page","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/26"},{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-add-edit-button","number":15,"title":"mz - adding \"edit commons\" button to users table for admins","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/15"}]
