
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-7
pull_requests: [{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-create-page","number":45,"title":"zc - admin create announcement page","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/45"},{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-createPage","number":44,"title":"zc - announcement list page for admin user","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/44"},{"author":{"id":"MDQ6VXNlcjUyOTMyMjQ1","is_bot":false,"login":"rkibel","name":"Ron Kibel"},"headRefName":"rkibel-homepageAndLeave","number":43,"title":"rk - homepage UI cleanup and \"leave\" button","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/43"},{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-announcement-button","number":36,"title":"zc - add announcements button on commons list page","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/36"},{"author":{"id":"U_kgDOBYEQGw","is_bot":false,"login":"nadavital","name":"Nadav Avital"},"headRefName":"nadav-AnnouncementBugFix","number":32,"title":"na - Fixed Announcement POST Bug","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/32"}]
