
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-7
pull_requests: [{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-tracker","number":24,"title":"zc - Latest Commit tracker","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/24"},{"author":{"id":"MDQ6VXNlcjMyMTUwMjk5","is_bot":false,"login":"james-y-f","name":"James Fu"},"headRefName":"james-profits-display","number":19,"title":"James - Added fixtures for Paged Profits Table","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/19"},{"author":{"id":"U_kgDOBYEQGw","is_bot":false,"login":"nadavital","name":"Nadav Avital"},"headRefName":"nadav-Homepage","number":18,"title":"na - started refactor of homepage","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/18"},{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-add-edit-button","number":15,"title":"mz - adding \"edit commons\" button to users table for admins","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/15"},{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-dev","number":13,"title":"zc - add custom toLocalISO convert function","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/pull/13"}]
